before:
  hooks:
  - ./Projectfile manpages
builds:
- id: gocat
  binary: bin/gocat
  main: cmd/gocat/main.go
- id: gocp
  binary: bin/gocp
  main: cmd/gocp/main.go
archives:
- format: tar.gz
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
  files:
  - man/man1/*
- format: zip
  replacements:
    windows: Windows
  files:
  - man/man1/*  # http://gnuwin32.sourceforge.net/packages/groff.htm
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  draft: true
