builds:
- id: gocat
  binary: bin/gocat
  main: cmd/gocat/main.go
- id: gocp
  binary: bin/gocp
  main: cmd/gocp/main.go
archives:
- format: tar.gz
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
  files:
  - man/man1
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
dockers:
  - image_templates:
    - "goodlittlescript/{{.ProjectName}}:{{ .Tag }}"
    - "goodlittlescript/{{.ProjectName}}:v{{ .Major }}"
    - "goodlittlescript/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}"
    - "goodlittlescript/{{.ProjectName}}:latest"
    binaries:
    - gocat
    - gocp
    builds:
    - gocat
    - gocp
    dockerfile: Dockerfile.release
