---
version: '3.6'
services:
  shell:
    image: ${REGISTRY:-}shell
    build:
      network: host
      context: .
      dockerfile: Dockerfile
      args:
        PACKAGE: ${PACKAGE:-pkg}
    command: sleep 31536000
    environment:
    - GITHUB_TOKEN
    volumes:
    - ./tmp/home:/home/appuser
    - .:/go/src/${PACKAGE:-pkg}
