---
version: '3.6'
services:
  shell:
    image: $IMAGE
    build:
      network: host
      context: .
      dockerfile: Dockerfile
      cache_from:
      - "${IMAGE}-cache-2"
    command: sleep 31536000
    working_dir: /go/src/$PACKAGE
    environment:
    - GITHUB_TOKEN
    volumes:
    - ./tmp/home:/home/appuser
    - .:/go/src/$PACKAGE
