---
version: '3.6'
services:
  shell:
    image: ${REGISTRY}shell
    build:
      network: host
      context: .
      dockerfile: Dockerfile
    command: sleep 31536000
    working_dir: /go/src/$PACKAGE
    environment:
    - GITHUB_TOKEN
    volumes:
    - ./tmp/home:/home/appuser
    - .:/go/src/$PACKAGE
