#!/bin/bash
# usage: ./Projectfile [command]
export REPO="goodlittlescript/gocat"
export PACKAGE="github.com/${REPO}"
export PACKAGE_URL="https://github.com/${REPO}"
export RELEASE_VERSION='0.0-rc8'
export RELEASE_DATE='2020-05-28'
export CACHE_REGISTRY="docker.pkg.github.com"
export CACHE_REPO_URL="${CACHE_REGISTRY}/${REPO}"

#
# workflow
#

images () {
  config_dir="$HOME/.kaniko"
  mkdir -p "$config_dir"
  touch "$config_dir/config.json"
  chmod 0600 "$config_dir/config.json"
  jq -n --arg registry "$CACHE_REGISTRY" --arg token "$GITHUB_TOKEN" '
    .auths["https://\($registry)"]["auth"] = ("goodlittlescript:\($token)" | @base64)
  ' > "$config_dir/config.json"

  docker run --rm \
    -v "$PWD:/workspace" \
    -v "$config_dir/config.json":/kaniko/.docker/config.json \
    gcr.io/kaniko-project/executor:latest \
    --dockerfile /workspace/Dockerfile \
    --destination "$CACHE_REPO_URL/example:shell" \
    --context dir:///workspace/ \
    --cache-repo "$CACHE_REPO_URL/cache" \
    --cache=true
}

up () {
  docker-compose up --detach
}

shell () {
  up && docker-compose exec shell /bin/bash
}

down () {
  docker-compose stop
}

clean () {
  docker-compose rm -s -f -v
}

run () {
  docker-compose run --rm shell "$@"
}

show () {
  docker-compose ps
}

logs () {
  docker-compose logs -f
}

release () {
  RELEASE_VERSION="${1?no version specified}"
  RELEASE_DATE="$(date +"%Y-%m-%d")"
  
  # normalize version
  RELEASE_VERSION="${RELEASE_VERSION#v}"

  # set new version
  sed -i "" \
    -e "/^export/s|RELEASE_VERSION=.*|RELEASE_VERSION='$RELEASE_VERSION'|" \
    -e "/^export/s|RELEASE_DATE=.*|RELEASE_DATE='$RELEASE_DATE'|" \
    ./Projectfile

  # print next steps
  cat >&2 <<DOC
Next steps:

  git status # double check your changes

  git commit -a -m "Release $RELEASE_VERSION"
  git push origin master

  git tag "v$RELEASE_VERSION"  
  git push origin --tags

A draft release will be created by GitHub Actions.  Take a look, write release
notes, and publish if desired.
DOC
}

#
# helpers
#

_lint () {
  gofmt -s -e -d .
}

_fix () {
  gofmt -s -w .
}

_test () {
  ./test/suite
}

_manpages () {
  mkdir -p man/man1
  ls cmd/*/MANPAGE.md |
  while read manpagemd
  do
    export COMMAND="$(basename "$(dirname "$manpagemd")")"
    envsubst '$COMMAND $PACKAGE_URL $RELEASE_VERSION $RELEASE_DATE' < "$manpagemd" |
    pandoc --standalone -f markdown -t man - > "man/man1/$COMMAND.1"
  done
}

_man () {
  manpages
  /usr/bin/man "man/man1/${1}.1"
}

#
# utility  
#

list () {
  compgen -A function
}

unfuncs="$(compgen -A "function" | grep "^_")"
if command -v docker-compose >/dev/null 2>&1
then eval "$(awk '{sub("_","");print $1"() {\nrun ./Projectfile "$1" \"\$@\"\n}\n"}' <<<"$unfuncs")"
else eval "$(declare -f $unfuncs | sed -e 's/^_//')"
fi
unset -f $unfuncs

if list | grep -qFx -- "${1:-}"
then "$@"
else
  if [ -z "$1" ]
  then printf "no command specified (try 'list')\n" >&2
  else printf "unknown command: %s\n" "$1" >&2
  fi
  exit 1
fi
