#!/bin/bash
# usage: ./Stackfile [command]
export PACKAGE=goodlittlescript.com/gocat

#
# develop
#

homefiles () {
  mkdir -p tmp/home
  cp ~/.gitconfig tmp/home
}

clean () {
	docker-compose down --remove-orphans --rmi all
}

images () {
	docker-compose build --compress --parallel --build-arg PACKAGE="${PACKAGE}"
}

test () {
	docker-compose run --rm shell ./test/suite
}

lint () {
	docker-compose run --rm shell test -z "$(gofmt -s -e -d . | tee /dev/stderr)"
}

fix () {
	docker-compose run --rm shell gofmt -s -w .
}

shell () {
	docker-compose run --rm shell /bin/bash
}

#
# deploy
#

artifacts () {
  images
  test
  lint
}

#
# utility
#

list () {
	compgen -A function 2>/dev/null
}

if list | grep -qFx "$1"
then "$@"
else
	if [ -z "$1" ]
	then printf "no command specified (try 'list')\n" >&2
	else printf "unknown command: %s\n" "$1" >&2
	fi
	exit 1
fi
